name: Check Run Workflow

on:
  check_run:
    types: [completed]

jobs:
  process_check_run:
    runs-on: ubuntu-latest
    steps:
      - name: Print Check Run Triggered
        run: echo "Check Run triggered after Simple Workflow completion"
