name: Fix Sonar Issues with Pixeebot
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch

permissions:
  id-token: write

jobs:
  share:
    name: Upload Sonar Results to Pixeebot
    runs-on: ubuntu-latest
    steps:
      - name: Upload Tool Results To Pixeebot
        uses: pixee/upload-tool-results-action@v1.0.1
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}

